// Project path: src/pages/admin/journal-entries/CreateJournalEntryPage.tsx
// Route: /accounting/journal-entries/create

import { useState } from "react";
import { useForm, useFieldArray } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useNavigate } from "react-router-dom";
import { useTranslation } from "react-i18next";
import toast from "react-hot-toast";
import { Plus, ArrowLeft } from "lucide-react";
import {
  createJournalEntrySchema,
  type CreateJournalEntryFormValues,
} from "../../../schemas/journalEntries.schema";
import { useCreateJournalEntry } from "../../../hooks/useJournalEntryMutations";
import { JournalLineRow } from "../../../components/admin/journal-entries/JournalLineRow";
import { BalanceIndicator } from "../../../components/admin/journal-entries/BalanceIndicator";
import axios from "axios";
import {handleErrors} from "../../../utils/HandleErrors"
import Optional from "@/components/common/Optional";

const emptyLine = { accountId: "", description: "", debit: 0, credit: 0 };

export function CreateJournalEntryPage() {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const createEntry = useCreateJournalEntry();

  const {
    control,
    register,
    handleSubmit,
    watch,
    setValue,
    getValues,
    reset,
    formState: { errors, isSubmitting },
  } = useForm<CreateJournalEntryFormValues>({
    resolver: zodResolver(createJournalEntrySchema),
    defaultValues: {
      entryDate: new Date().toISOString().slice(0, 10),
      description: "",
      lines: [emptyLine, emptyLine],
    },
  });

  let isValid: boolean = false;
  const values = getValues().lines;
  values?.forEach((val) => {
    if(!val.accountId || (val.credit === 0 && val.debit === 0) || (val.credit> 0 && val.debit > 0)){
      isValid = true;
      return
    }else {
      isValid = false;
    }
  })

  const { fields, append, remove, insert } = useFieldArray({
    control,
    name: "lines",
  });

  const lines = watch("lines");
  const totalDebit = lines.reduce((s, l) => s + (Number(l.debit) || 0), 0);
  const totalCredit = lines.reduce((s, l) => s + (Number(l.credit) || 0), 0);

  const [stayAfterSave, setStayAfterSave] = useState(false);

  const handleLineChange = (
    index: number,
    field: "accountId" | "description" | "debit" | "credit",
    value: string | number
  ) => {
    setValue(`lines.${index}.${field}` as const, value as never, {
      shouldValidate: true,
    });
  };

  const onSubmit = async (values: CreateJournalEntryFormValues) => {

    try {
      const created = await createEntry.mutateAsync(values);
      toast.success(t("journalEntries.toasts.created"));
      if (stayAfterSave) {
        reset({
          entryDate: new Date().toISOString().slice(0, 10),
          description: "",
          lines: [emptyLine, emptyLine],
        });
      } else {
        navigate(`/accounting/journal-entries/${created.id}`);
      }
    } catch (err) {
      if (axios.isAxiosError(err)) {
        handleErrors(err.response?.data.errors)
      } else {
        console.error(err);
      }

    }
  };

  const linesError =
    typeof errors.lines?.message === "string" ? errors.lines.message : null;


  return (
    <form onSubmit={handleSubmit(onSubmit)} className="flex flex-col">
      <div className="flex flex-col gap-6 p-6 pb-28">
        <button
          type="button"
          onClick={() => navigate("/accounting/journal-entries")}
          className="flex w-fit items-center gap-1.5 text-sm text-[--ink-secondary] hover:text-[--ink-primary]"
        >
          <ArrowLeft size={16} className="rtl:rotate-180" />
          {t("journalEntries.details.back")}
        </button>

        <div>
          <h1 className="text-2xl font-semibold text-[--ink-primary]">
            {t("journalEntries.create.title")}
          </h1>
          <p className="mt-1 text-sm text-[--ink-secondary]">
            {t("journalEntries.create.subtitle")}
          </p>
        </div>

        <section className="grid grid-cols-1 gap-4 rounded-lg border border-[--hairline] bg-[--panel] p-5 sm:grid-cols-3">
          <div>
            <label className="mb-1 block text-sm text-[--ink-secondary]">
              {t("journalEntries.fields.entryNumber")}
            </label>
            <input
              disabled
              value={t("journalEntries.create.autoGenerated")}
              className="w-full rounded-md border border-[--hairline] bg-[--sunken] px-3 py-2 text-sm text-[--ink-tertiary]"
            />
          </div>
          <div>
            <label className="mb-1 block text-sm text-[--ink-secondary]">
              {t("journalEntries.fields.entryDate")}
            </label>
            <input
              type="date"
              {...register("entryDate")}
              className="w-full rounded-md border border-[--hairline] bg-[--sunken] px-3 py-2 text-sm outline-none focus:border-[--signal] focus:ring-2 focus:ring-[--synapse]/30"
            />
            {errors.entryDate && (
              <p className="mt-1 text-xs text-[--error]">
                {t(errors.entryDate.message as string)}
              </p>
            )}
          </div>
          <div className="sm:col-span-1">
            <label className="mb-1 block text-sm text-[--ink-secondary]">
              {t("journalEntries.fields.description")}
              <Optional/>
            </label>
            <input
              {...register("description")}
              className="w-full rounded-md border border-[--hairline] bg-[--sunken] px-3 py-2 text-sm outline-none focus:border-[--signal] focus:ring-2 focus:ring-[--synapse]/30"
            />
          </div>
        </section>

        <section className="flex flex-col gap-3">
          <div className="flex items-center justify-between">
            <h2 className="text-sm font-semibold text-[--ink-primary]">
              {t("journalEntries.create.journalLines")}
            </h2>
            <button
              type="button"
              onClick={() => append(emptyLine)}
              className="inline-flex items-center gap-1.5 rounded-md border border-[--hairline] px-3 py-1.5 text-sm font-medium text-[--ink-primary] hover:bg-[--sunken]"
            >
              <Plus size={15} />
              {t("journalEntries.lines.addRow")}
            </button>
          </div>

          <div className="flex flex-col gap-2">
            {fields.map((field, index) => (
              <JournalLineRow
                key={field.id}
                index={index}
                accountId={lines[index]?.accountId ?? ""}
                description={lines[index]?.description ?? ""}
                debit={lines[index]?.debit ?? 0}
                credit={lines[index]?.credit ?? 0}
                onChange={handleLineChange}
                onRemove={remove}
                onDuplicate={(i) => insert(i + 1, lines[i])}
                canRemove={fields.length > 2}
              />
            ))}
          </div>

          {linesError && (
            <p className="text-sm text-[--error]">{t(linesError)}</p>
          )}
        </section>
      </div>

      <div className="fixed inset-x-0 bottom-0 flex flex-col gap-3 border-t border-[--hairline] bg-[--panel] px-6 py-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex flex-wrap items-center gap-4">
          <div className="flex gap-4 text-sm">
            <div>
              <p className="text-[--ink-tertiary]">{t("journalEntries.totals.debit")}</p>
              <p className="font-semibold text-[--ink-primary]">{totalDebit.toFixed(2)}</p>
            </div>
            <div>
              <p className="text-[--ink-tertiary]">{t("journalEntries.totals.credit")}</p>
              <p className="font-semibold text-[--ink-primary]">{totalCredit.toFixed(2)}</p>
            </div>
          </div>
          <BalanceIndicator totalDebit={totalDebit} totalCredit={totalCredit} />
        </div>

        <div className="flex items-center z-50 gap-3">
          <label className="flex items-center gap-2 text-sm text-[--ink-secondary]">
            <input
              type="checkbox"
              checked={stayAfterSave}
              onChange={(e) => setStayAfterSave(e.target.checked)}
              className="accent-[--signal]"
            />
            {t("journalEntries.create.stayAndCreateAnother")}
          </label>
          <button
            type="button"
            onClick={() => navigate("/accounting/journal-entries")}
            className="rounded-md px-4 py-2 text-sm font-medium text-[--ink-secondary] hover:bg-[--sunken]"
          >
            {t("common.actions.cancel")}
          </button>
          <button
            type="submit"
            disabled={isSubmitting || isValid}
            className={`rounded-md bg-[--signal] disabled:opacity-60 disabled:cursor-not-allowed px-4 py-2 text-sm font-medium text-white hover:bg-[--signal-hover] `}
          >
            {
              isSubmitting ? t("journalEntries.actions.creating") : t("journalEntries.actions.create")
            }
          </button>
        </div>
      </div>
    </form>
  );
}
